import { NgModule } from "@angular/core";
import { NativeScriptRouterModule } from "nativescript-angular/router";
import { Routes } from "@angular/router";

import { AutoGeneratedComponent } from "./auto-generated/auto-generated.component";
import { LayoutComponent } from "./layout/layout.component";
import { HomeComponent } from "./home/home.component";
import { ApplicationDetailsComponent } from "./application-details/application-details.component";
import { LoginGuard } from "./login.guard";
import { LoginComponent } from "./login/login.component";
import { LoggedOutGuard } from "./logged-out.guard";

const routes: Routes = [
  { path: "", redirectTo: "home", pathMatch: "full" },
  {
    path: "",
    component: LayoutComponent,
    children: [
      { path: "home", component: HomeComponent },
      { path: "details/:id", component: ApplicationDetailsComponent }
    ],
    canActivate: [LoginGuard]
  },
  {
    path: "login",
    component: LoginComponent,
    canActivate: [LoggedOutGuard]
  }
];

@NgModule({
  imports: [NativeScriptRouterModule.forRoot(routes)],
  exports: [NativeScriptRouterModule]
})
export class AppRoutingModule {}
